spring:
  datasource:
    url: jdbc:mysql://39.96.199.227:90/platform_test2?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: ywyz
    password: "yw031235"
server:  address: 192.168.0.55
  port: 82