spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: "root"
server:  address: 192.168.0.55
  port: 82