server:
#  address: 192.168.0.55
  port: 8002
spring:  application:    name: cloud-payment-service
  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: "root"
    
eureka:
  client:
    # false 表示是否向注册中心注册自己
    register-with-eureka: true 
    # 是否从eurekaServer抓取已有的注册信息，默认为true，单节点无所谓。集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

mybatis:  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.springcloud.entities
