server:
  port: 7001
eureka:  instance:    hostname: eureka7001.com
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false 
    # false 表示自己是注册中心，职责是维护服务实例，不需要检索服务
    fetch-registry: false
    service-url:
      #设置于eureka server 交互的地址查询服务和注册服务都需要依赖这个地址      defaultZone: http://eureka7002.com:7002/eureka/